/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type MlappAutoscale struct {
	Enabled                  bool  `json:"enabled,omitempty"`
	MaxReplicas              int32 `json:"max_replicas,omitempty"`
	MinReplicas              int32 `json:"min_replicas,omitempty"`
	TargetAverageUtilization int32 `json:"target_average_utilization,omitempty"`
}
