/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type MlappVolumeMount struct {
	GitRevision string `json:"gitRevision,omitempty"`
	MountPath   string `json:"mountPath,omitempty"`
	Name        string `json:"name"`
	ReadOnly    bool   `json:"readOnly,omitempty"`
	SubPath     string `json:"subPath,omitempty"`
}
