/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type MlappVolume struct {
	ClusterStorage        string                               `json:"clusterStorage,omitempty"`
	Dataset               *MlappDatasetSource                  `json:"dataset,omitempty"`
	DatasetFS             *MlappDatasetFsSource                `json:"datasetFS,omitempty"`
	EmptyDir              *V1EmptyDirVolumeSource              `json:"emptyDir,omitempty"`
	FlexVolume            *V1FlexVolumeSource                  `json:"flexVolume,omitempty"`
	GitRepo               *MlappGitRepoVolumeSource            `json:"gitRepo,omitempty"`
	HostPath              *V1HostPathVolumeSource              `json:"hostPath,omitempty"`
	IsLibDir              bool                                 `json:"isLibDir,omitempty"`
	IsTrainLogDir         bool                                 `json:"isTrainLogDir,omitempty"`
	IsWorkspaceLocal      bool                                 `json:"isWorkspaceLocal,omitempty"`
	Model                 *MlappModelSource                    `json:"model,omitempty"`
	MountPath             string                               `json:"mountPath,omitempty"`
	Name                  string                               `json:"name"`
	Nfs                   *V1NfsVolumeSource                   `json:"nfs,omitempty"`
	PersistentStorage     *MlappPersistentStorage              `json:"persistentStorage,omitempty"`
	PersistentVolumeClaim *V1PersistentVolumeClaimVolumeSource `json:"persistentVolumeClaim,omitempty"`
	ReadOnly              bool                                 `json:"readOnly,omitempty"`
	S3bucket              *MlappS3BucketSource                 `json:"s3bucket,omitempty"`
	SubPath               string                               `json:"subPath,omitempty"`
}
