/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type ModelsTaskFormElement struct {
	Elements []ModelsTaskFormElement     `json:"elements,omitempty"`
	Hidden   bool                        `json:"hidden,omitempty"`
	Label    string                      `json:"label,omitempty"`
	ListType string                      `json:"listType,omitempty"`
	Name     string                      `json:"name,omitempty"`
	Options  []string                    `json:"options,omitempty"`
	Required bool                        `json:"required,omitempty"`
	Type_    string                      `json:"type,omitempty"`
	Value    *ModelsTaskFormElementValue `json:"value,omitempty"`
	Width    int32                       `json:"width,omitempty"`
}
