/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type ModelsInferenceVersion struct {
	Created               string                  `json:"Created"`
	DefaultValues         *interface{}            `json:"DefaultValues"`
	EdgeConfigTemplate    string                  `json:"EdgeConfigTemplate"`
	Form                  []ModelsTaskFormElement `json:"Form"`
	ServingConfigTemplate string                  `json:"ServingConfigTemplate"`
	Updated               string                  `json:"Updated"`
	Version               string                  `json:"Version"`
}
