/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type ModelsServing struct {
	ApplicationDisplayName        string                                `json:"ApplicationDisplayName,omitempty"`
	ApplicationName               string                                `json:"ApplicationName,omitempty"`
	ApplicationSource             string                                `json:"ApplicationSource,omitempty"`
	ApplicationSourceSubPath      string                                `json:"ApplicationSourceSubPath,omitempty"`
	Build                         string                                `json:"Build,omitempty"`
	ClusterID                     string                                `json:"ClusterID,omitempty"`
	Config                        *MlappUniversalServing                `json:"Config,omitempty"`
	ContainersCount               int32                                 `json:"ContainersCount,omitempty"`
	Description                   string                                `json:"Description,omitempty"`
	Disabled                      bool                                  `json:"Disabled,omitempty"`
	DisplayName                   string                                `json:"DisplayName,omitempty"`
	GPUUsed                       int32                                 `json:"GPUUsed,omitempty"`
	Gallery                       bool                                  `json:"Gallery,omitempty"`
	GalleryTags                   []string                              `json:"GalleryTags,omitempty"`
	Health                        string                                `json:"Health,omitempty"`
	HealthError                   string                                `json:"HealthError,omitempty"`
	ID                            string                                `json:"ID,omitempty"`
	InferenceForm                 []ModelsTaskFormElement               `json:"InferenceForm,omitempty"`
	InferenceName                 string                                `json:"InferenceName,omitempty"`
	InferenceStreams              []ModelsTaskFormElementStreamExtended `json:"InferenceStreams,omitempty"`
	InferenceValues               *interface{}                          `json:"InferenceValues,omitempty"`
	InferenceVersion              string                                `json:"InferenceVersion,omitempty"`
	InferenceWorkspaceDisplayName string                                `json:"InferenceWorkspaceDisplayName,omitempty"`
	InferenceWorkspaceName        string                                `json:"InferenceWorkspaceName,omitempty"`
	InnerAddress                  string                                `json:"InnerAddress,omitempty"`
	Name                          string                                `json:"Name,omitempty"`
	Picture                       string                                `json:"Picture,omitempty"`
	Status                        string                                `json:"Status,omitempty"`
	StatusMessage                 string                                `json:"StatusMessage,omitempty"`
	Task                          string                                `json:"Task,omitempty"`
	Type_                         string                                `json:"Type,omitempty"`
	UserDisplayName               string                                `json:"UserDisplayName,omitempty"`
	UserID                        string                                `json:"UserID,omitempty"`
	UserLogin                     string                                `json:"UserLogin,omitempty"`
	WorkspaceDisplayName          string                                `json:"WorkspaceDisplayName,omitempty"`
	WorkspaceName                 string                                `json:"WorkspaceName,omitempty"`
}
