/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type MlappServingSpec struct {
	Model       string                      `json:"model,omitempty"`
	Options     *MlappServingSpecOptions    `json:"options,omitempty"`
	OutFilter   []string                    `json:"outFilter,omitempty"`
	OutMimeType string                      `json:"outMimeType,omitempty"`
	Params      []MlappServingSpecParam     `json:"params,omitempty"`
	RawInput    bool                        `json:"rawInput,omitempty"`
	Response    []MlappServingResponseParam `json:"response,omitempty"`
	Signature   string                      `json:"signature,omitempty"`
	Template    string                      `json:"template,omitempty"`
}
