/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type MlappResourceRequest struct {
	Accelerators *MlappResourceAccelerators `json:"accelerators"`
	Limits       *DealerclientResourceLimit `json:"limits,omitempty"`
	Requests     *DealerclientResourceLimit `json:"requests,omitempty"`
}
