/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type ModelsTaskFormElementStreamExtended struct {
	Description string            `json:"description,omitempty"`
	Input       string            `json:"input,omitempty"`
	Key         string            `json:"key,omitempty"`
	Output      string            `json:"output,omitempty"`
	Params      map[string]string `json:"params,omitempty"`
	StreamUrl   string            `json:"stream_url,omitempty"`
}
