/*
 * Kibernetika project, backend component
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package kclient

type MlappServingSpecParam struct {
	Label   string                      `json:"label,omitempty"`
	Name    string                      `json:"name,omitempty"`
	Options []string                    `json:"options,omitempty"`
	Type_   string                      `json:"type,omitempty"`
	Value   *MlappServingSpecParamValue `json:"value,omitempty"`
}
